runtime: java17
entrypoint: java -jar fd-applet-fat.jar

instance_class: F4
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_pending_latency: 15s
  target_cpu_utilization: 0.95
  max_concurrent_requests: 1000
